import os
import sys
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage, PageBreak, HRFlowable, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super(NumberedCanvas, self).showPage()
        super(NumberedCanvas, self).save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#718096"))
        
        # Header (Pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 11 * inch - 36, "ULTRA B (ウルトラB) — The Complete Character & Series Encyclopedia")
            self.setStrokeColor(colors.HexColor("#CBD5E0"))
            self.setLineWidth(0.5)
            self.line(54, 11 * inch - 42, 8.5 * inch - 54, 11 * inch - 42)
            
        # Footer
        footer_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(8.5 * inch - 54, 30, footer_text)
        self.drawString(54, 30, "Generated by Pratham AI — Created by Pratham Sinha under the supervision of Akriti & Aditi Aishwaryam")
        self.setStrokeColor(colors.HexColor("#CBD5E0"))
        self.setLineWidth(0.5)
        self.line(54, 42, 8.5 * inch - 54, 42)
        
        self.restoreState()

def build_pdf(filename="ultra_b_characters_encyclopedia.pdf"):
    doc = SimpleDocTemplate(
        filename,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=50,
        bottomMargin=50
    )
    
    styles = getSampleStyleSheet()
    
    # Custom typography styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#1A202C"),
        alignment=1 # Center
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#E53E3E"), # Crimson red
        alignment=1
    )
    
    meta_style = ParagraphStyle(
        'DocMeta',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#4A5568"),
        alignment=1
    )
    
    h1_style = ParagraphStyle(
        'SectionH1',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#2B6CB0"),
        spaceBefore=10,
        spaceAfter=6
    )
    
    card_title_style = ParagraphStyle(
        'CardTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#1A365D")
    )
    
    card_badge_style = ParagraphStyle(
        'CardBadge',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#C53030")
    )
    
    card_meta_style = ParagraphStyle(
        'CardMeta',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#4A5568")
    )
    
    card_body_style = ParagraphStyle(
        'CardBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor("#2D3748")
    )
    
    story_style = ParagraphStyle(
        'StoryText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor("#2D3748")
    )

    story = []
    
    # Title Header Block
    story.append(Paragraph("<b>ULTRA B (ウルトラB)</b>", title_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph("<b>THE DEFINITIVE CHARACTER GUIDE & SERIES ENCYCLOPEDIA</b>", subtitle_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph("Classic Masterpiece by Fujiko Fujio &#x24B6; (Motoo Abiko) • Shin-Ei Animation (118 Episodes & Movie)", meta_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#E53E3E"), spaceAfter=12))
    
    # Overview banner with Poster Image
    has_poster = os.path.exists("ub_poster.jpg")
    
    overview_text = (
        "<b>Series Overview:</b><br/>"
        "<i>Ultra B</i> (ウルトラB, Urutora B) is a celebrated comedic science-fiction manga and anime created by legendary "
        "manga artist <b>Fujiko Fujio &#x24B6;</b> (co-creator of <i>Doraemon</i>, creator of <i>Ninja Hattori</i>, <i>Perman</i>, and <i>Kaibutsu-kun</i>). "
        "Serialized in Chuokoron-sha's <i>Fujiko Fujio Land</i> from 1984 to 1989 across 133 chapters (11 volumes), it was animated by <b>Shin-Ei Animation</b> into a massively beloved 118-episode anime series (1987–1989) "
        "and a 1988 theatrical feature film (<i>Black Hole kara no Dokusaisha BB!!</i>).<br/><br/>"
        "<b>Plot Essence:</b><br/>"
        "The story begins when elementary school student Michio Suzumoto discovers a mysterious cocoon-shaped UFO in the forest. "
        "Inside lies an eccentric alien baby sporting futuristic winged red sunglasses and possessing extraordinary supernatural powers: <b>Ultra B (UB)</b>. "
        "UB uses his hypnotic mind-waves to blend into the Suzumoto family as their adorable infant. Fueling his mind-boggling psychic abilities by gulping down cartons of cow's milk, UB turns Michio's ordinary neighborhood upside down with psychic mischief, hilarious adventures, and heroic showdowns against cosmic rivals!"
    )
    
    if has_poster:
        poster_img = RLImage("ub_poster.jpg", width=1.6*inch, height=2.53*inch)
        intro_table = Table(
            [[poster_img, Paragraph(overview_text, story_style)]],
            colWidths=[1.8*inch, 5.2*inch]
        )
        intro_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F7FAFC")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#E2E8F0")),
            ('PADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(intro_table)
    else:
        story.append(Paragraph(overview_text, story_style))
        
    story.append(Spacer(1, 14))
    
    # Characters Data
    characters = [
        {
            "name": "Ultra B (UB / ユービー)",
            "role": "Titular Protagonist & Alien Baby Extraordinaire",
            "voice": "Yūko Mita (三田ゆう子)",
            "image": "ub_character.jpg" if os.path.exists("ub_character.jpg") else "ub_poster.jpg",
            "traits": "Winged Red Sunglasses • Cocoon UFO • Star-Shaped Mole • Powered by 1L Milk Cartons",
            "desc": (
                "The heart and soul of the franchise. UB is an enigmatic extraterrestrial infant who crash-landed on Earth inside a high-tech "
                "cocoon-shaped spacecraft. Beneath his trademark red visor glasses and adorable blue star-shaped mole lies incomprehensible psionic power, "
                "including psychokinesis, levitation, mind-control, and teleportation. He immediately hypnotized the Suzumoto household into accepting him as a beloved family infant. "
                "UB can easily outsmart adult champions at card games like Blackjack, but hilariously meets his match in Michio's mom! He charges his cosmic superpowers by guzzling 1-liter milk cartons, and while he fears black cats (Tangoro), he will bravely defend Earth against alien tyrants."
            )
        },
        {
            "name": "Michio Suzumoto (鈴本 ミチオ)",
            "role": "Elementary Boy & Earthly Foster Guardian",
            "voice": "Chiyoko Kawashima (川島千代子)",
            "image": "ub_poster.jpg",
            "traits": "Signature Yellow 'M' Shirt • Clumsy & Good-Hearted • UB's Best Friend",
            "desc": (
                "An average, good-natured elementary school boy attending Yumegaoka Elementary. Michio was exploring the wooded hills behind town when he uncovered "
                "UB's glowing cocoon pod. Despite having poor athletic skills, habitually scoring zero marks on surprise exams, and frequently arriving late to Mr. Kabayama's class, "
                "Michio possesses deep compassion. He assumes the role of UB's elder brother and Earth guardian. Although UB's psychic antics plunge Michio into nonstop chaos, "
                "their brotherly bond is unbreakable, standing together through thick and thin."
            )
        },
        {
            "name": "Kazuyo Suzumoto (鈴本 カズヨ - Mama)",
            "role": "Michio's Formidable & Cheerful Mother",
            "voice": "Masako Nozawa (野沢雅子) / Gara Takashima",
            "image": None,
            "traits": "Household Matriarch • The Only One Who Beats UB at Cards • Loving Disciplinarian",
            "desc": (
                "Michio's energetic, robust mother whom UB affectionately calls 'Papa-Mama'. She runs the Suzumoto household with an iron ladle and warmth. "
                "Despite UB possessing vast intergalactic intellect and psychic reading powers, Kazuyo is the single human in the universe UB can never defeat in poker or Blackjack! "
                "Though she frets about her weight and Michio's dreadful report cards, she lavishes maternal love and endless milk bottles on baby UB."
            )
        },
        {
            "name": "Shinichi Suzumoto (鈴本 進一 - Papa)",
            "role": "Michio's Diligent Salaryman Father",
            "voice": "Kaneta Kimotsuki (肝付兼太)",
            "image": None,
            "traits": "Classic 'Mr. Koike' Fujiko Face • Passionate Golfer • Booby Prize Champion",
            "desc": (
                "Michio's father and a hard-working office salaryman, called 'Papa-Papa' by UB. Fans will instantly recognize his iconic wavy hair and ramen-loving face "
                "inspired by Fujiko Fujio's legendary archetype 'Mr. Koike'. He is obsessed with weekend golf tournaments but invariably finishes in last place (earning the booby prize). "
                "A gentle father who grew up reading classic Osamu Tezuka manga, he warmly embraces UB into his home."
            )
        },
        {
            "name": "Takemi Aoba (青葉 タケミ)",
            "role": "Class Sweetheart & Michio's Crush",
            "voice": "Naoko Matsui (松井菜桜子)",
            "image": None,
            "traits": "Gentle & Intelligent • Kind to Michio • Adored by UB ('B-chan')",
            "desc": (
                "The bright, kind, and attractive classmate of Michio at Yumegaoka Elementary. Takemi treats Michio with genuine warmth and patience, "
                "never mocking his academic mishaps. In early chapters she affectionately nicknames UB 'B-chan' (or 'U-bo-chan'). Both Michio and Tosaka compete fiercely "
                "for her attention, but Takemi always remains gracious and compassionate."
            )
        },
        {
            "name": "Tateo Tosaka (戸坂 タテオ - Tosaka-kun)",
            "role": "Wealthy, Rooster-Faced Rival",
            "voice": "Shigeru Chiba (千葉繁)",
            "image": None,
            "traits": "Rooster Crest Hair • Screams 'Ko-keee!' • Rich Snob & Boaster",
            "desc": (
                "The proud, boastful boy from a wealthy family whose slicked-up hairdo and facial expressions mimic a rooster. Known for his hysterical vocal tic 'Ko-keee!' "
                "voiced by anime voice legend Shigeru Chiba. Tosaka loves flaunting expensive imports, high-tech gadgets, and foreign souvenirs to impress Takemi and belittle Michio, "
                "only for UB's psychic tricks to humiliate him in delightfully comical ways."
            )
        },
        {
            "name": "Daibutsu Narano (奈良野 大仏 - Daibutsu)",
            "role": "Giant, Gentle Temple Son",
            "voice": "Sukekiyo Kameyama (亀山助清)",
            "image": None,
            "traits": "Temple Monk's Son • Buddha-like Demeanor • Finishes sentences with '~dabutsu'",
            "desc": (
                "A large, gentle giant classmate whose family oversees the town's Buddhist temple. True to his name (meaning Giant Buddha), Daibutsu is calm, "
                "philosophical, and slow to anger, often concluding his sentences with '~dabutsu'. He hangs out closely with his psychic baby nephew Jizo. "
                "Unlike the rest of town, Daibutsu casually witnesses UB's supernatural powers without panicking, serving as a trustworthy ally."
            )
        },
        {
            "name": "Mr. Daikichi Kabayama (加馬山 大吉 先生)",
            "role": "Strict Class Teacher (Hippopotamus Face)",
            "voice": "Osamu Katō (加藤治)",
            "image": None,
            "traits": "Hippo-Like Jaw • No-Nonsense Educator • Fierce Disciplinarian",
            "desc": (
                "Michio's elementary homeroom teacher whose imposing, hippo-shaped countenance commands instant silence. A fierce enemy of tardiness, forgotten homework, "
                "and daydreaming, he regularly scolds Michio with booming thunderclaps. Deep down, however, Mr. Kabayama cares about his students and wants Michio to discover his true potential."
            )
        },
        {
            "name": "Fukuno Family: Dōta & Dōji (福野 胴太 & 胴二)",
            "role": "Superhuman Kindergarten Brothers & UB's Playmates",
            "voice": "Dota: Kazuyo Aoki • Doji: Rei Sakuma",
            "image": None,
            "traits": "Unstoppable Toddler Brawn • Kewpie Doll Hair (Doji) • Rough-and-Tumble Pals",
            "desc": (
                "The sons of Kazuyo's old school friend, Fukuko. Dota, despite being in kindergarten, boasts unbelievable physical strength capable of tossing high-school delinquents over his shoulder! "
                "His baby brother Doji resembles a kewpie doll and is even wilder, pulling pranks on Michio. Despite the mayhem, Dota, Doji, and UB form a fierce toddler brotherhood of mischief."
            )
        },
        {
            "name": "Kiriko-chan (キリコちゃん) & Kasumi Kirimachi",
            "role": "UB's High-Society Baby Girlfriend",
            "voice": "Natsuko Hashima (羽島奈津子)",
            "image": None,
            "traits": "1-Year-Old Child Model • UB's Beloved Sweetheart • Elite Society Infant",
            "desc": (
                "An angelic 1-to-2-year-old baby girl who appears on television broadcasts. UB immediately fell head-over-heels in love upon seeing her on TV! "
                "He used his teleportation to break into her mansion in the middle of the night to woo her, winning her affection. In the theatrical movie and Hawaii special, "
                "UB's devotion to rescuing and accompanying Kiriko drives the grand storyline."
            )
        },
        {
            "name": "Tangoro (タンゴロー)",
            "role": "The Feared Black Alley Cat (UB's Arch-Nemesis)",
            "voice": "Kenichi Ogata (緒方賢一)",
            "image": None,
            "traits": "Stray Black Cat • Anime Exclusive • Immune to Alien Intimidation",
            "desc": (
                "A sly, tough black street cat prowling Yumegaoka's alleys. Despite UB having godlike psychokinetic powers that can blast meteors, "
                "UB possesses an extreme, hysterical phobia of black cats! Tangoro frequently ambushes or stares down UB, reducing the cosmic alien prodigy "
                "to a shivering, milk-guzzling baby."
            )
        },
        {
            "name": "Dictator BB (ベーベー / B・B)",
            "role": "Intergalactic Masked Baby Conqueror & Cosmic Rival",
            "voice": "Chika Sakamoto (坂本千夏)",
            "image": None,
            "traits": "Iron-Masked Evil Baby • Commands Skull Butterflies • Rival from the Black Hole",
            "desc": (
                "The primary antagonist featured in the blockbuster feature film <i>Black Hole kara no Dokusaisha BB!!</i> and the manga finale <i>Revenge of Prince BB</i>. "
                "BB is a cunning alien baby wearing an ominous skull-like battle helmet who arrives to conquer Earth by brainwashing babies through television airwaves. "
                "Accompanied by his monstrous war bird Gédon and an army of hypnotizing Skull Butterflies, BB poses UB's greatest cosmic challenge until an earthly cold virus fells him!"
            )
        },
        {
            "name": "Muscle Bird (マッスルバード)",
            "role": "Bodybuilder War-Bird & Suzumoto Roof Guardian",
            "voice": "Manga Featured Specialist",
            "image": None,
            "traits": "Muscular Human Biceps on Wings • Hatched from BB's Egg • Roof Sentry",
            "desc": (
                "A bizarre creature born from an egg that UB brought home from Dictator BB's space cruiser. When it hatched, it developed into a bird with huge, "
                "hyper-muscular human arms instead of regular avian wings! Kazuyo refused to let it live in the living room, so it guards the Suzumoto household from the rooftop, "
                "lending its massive physical punch whenever danger looms."
            )
        }
    ]
    
    story.append(Paragraph("<b>COMPREHENSIVE CHARACTER ROSTER & DOSSIER</b>", h1_style))
    story.append(Spacer(1, 4))
    
    # Render Character Cards
    for char in characters:
        card_content = []
        
        # Header line: Name + Role
        header_text = f"<b>{char['name']}</b> &nbsp;|&nbsp; <font color='#C53030'><b>{char['role']}</b></font>"
        card_content.append(Paragraph(header_text, card_title_style))
        card_content.append(Spacer(1, 2))
        
        meta_line = f"<b>Voice:</b> {char['voice']} &nbsp;&nbsp;•&nbsp;&nbsp; <b>Key Features:</b> {char['traits']}"
        card_content.append(Paragraph(meta_line, card_meta_style))
        card_content.append(Spacer(1, 4))
        card_content.append(Paragraph(char['desc'], card_body_style))
        
        # Check if character has dedicated image
        if char['image'] and os.path.exists(char['image']):
            img = RLImage(char['image'], width=1.1*inch, height=1.35*inch)
            table_data = [[img, card_content]]
            col_widths = [1.25*inch, 5.75*inch]
        else:
            table_data = [[card_content]]
            col_widths = [7.0*inch]
            
        char_table = Table(table_data, colWidths=col_widths)
        char_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FFFFFF")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E0")),
            ('PADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        
        story.append(KeepTogether([char_table, Spacer(1, 8)]))
        
    # Series Quick Reference & Production Credits Table
    story.append(Spacer(1, 10))
    story.append(Paragraph("<b>SERIES PRODUCTION ARCHIVE & HISTORICAL HIGHLIGHTS</b>", h1_style))
    story.append(Spacer(1, 4))
    
    archive_data = [
        [Paragraph("<b>Category</b>", card_title_style), Paragraph("<b>Production Details & Milestones</b>", card_title_style)],
        [Paragraph("<b>Original Manga</b>", card_body_style), Paragraph("Written & Illustrated by Fujiko Fujio &#x24B6; (Motoo Abiko). Serialized in <i>Fujiko Fujio Land</i> (Chuo Koronsha), 133 Chapters (1984–1989). 11 Volumes.", card_body_style)],
        [Paragraph("<b>Anime Broadcast</b>", card_body_style), Paragraph("118 Episodes produced by Shin-Ei Animation, broadcast on TV Asahi (1987–1989). Aired internationally across Asia and India on Hungama TV & Disney XD.", card_body_style)],
        [Paragraph("<b>Theatrical Movie</b>", card_body_style), Paragraph("<i>Ultra B: Black Hole kara no Dokusaisha BB!!</i> (1988). Groundbreaking stereoscopic 3D film screened alongside <i>Doraemon: The Record of Nobita's Parallel Visit to the West</i>.", card_body_style)],
        [Paragraph("<b>Music & Theme</b>", card_body_style), Paragraph("Opening Theme: <i>'Babi Babi Babi-boo Ultra B'</i> composed by master Shunsuke Kikuchi, performed by Yūko Mita & Koorogi '73.", card_body_style)],
        [Paragraph("<b>Himi City Memorial</b>", card_body_style), Paragraph("Official bronze monument of Ultra B unveiled on August 27, 2022, in creator Motoo Abiko's birthplace of Himi City, Toyama Prefecture.", card_body_style)]
    ]
    
    archive_table = Table(archive_data, colWidths=[1.8*inch, 5.2*inch])
    archive_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#EDF2F7")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E0")),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    
    story.append(archive_table)
    
    # Build Document
    doc.build(story, canvasmaker=NumberedCanvas)
    print("PDF build successful: " + filename)

if __name__ == "__main__":
    build_pdf()
