services:
  - type: web
    name: pratham-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --threads 2 --timeout 120
    plan: free
    envVars:
      - key: INITIAL_ADMIN_EMAIL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: DEEPINFRA_API_KEY
        sync: false
      - key: FIREWORKS_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: GITHUB_API_KEY
        sync: false
      - key: SAMBANOVA_API_KEY
        sync: false